
version: 0.0.{build}

branches:
    only:
        - release
        - test

skip_non_tags: true

init:
    - cmd: choco install msys2
    - cmd: mklink /J C:\msys64 C:\tools\msys64
    - cmd: set MSYS_DIR=C:\msys64
    - cmd: set MINGW_DIR=%MSYS_DIR%\mingw64
    - cmd: set PATH=%MINGW_DIR%\bin;%MSYS_DIR%\usr\bin;%PATH%
    - cmd: pacman -S mingw-w64-x86_64-gtk3
    - cmd: pacman -S mingw-w64-x86_64-gtkmm3

clone_folder: C:\gtk-test

matrix:
    fast_finish: true

services:
    - msys
    - bash
    - mingw

install:
    - cmd: npm install

platform:
    - Any CPU

configuration: Release

build_script:
    - cmd: npm run build
