
version: 0.0.{build}

branches:
    only:
        - release
        - test

skip_non_tags: true

init:
    - echo Current Directory is %cd%
    - dir
    - echo Content of drive C
    - dir ..
    - set MSYS_DIR=C:\msys64
    - set MINGW_DIR=%MSYS_DIR%\mingw64
    - set PATH=%MINGW_DIR%\bin;%MSYS_DIR%\usr\bin;%PATH%
    - pacman -S mingw-w64-x86_64-gtk3
    - pacman -S mingw-w64-x86_64-gtkmm3

clone_folder: C:\gtk-test

matrix:
    fast_finish: true

services:
    - msys
    - bash
    - mingw

install:
    - cmd: npm install

platform:
    - Any CPU

configuration: Release

build_script:
    - cmd: npm run build
