
version: v0.0.0.appveyor.{build}

branches:
    only:
        - release
        - test

skip_non_tags: true

init:
    - echo Before Build Test %TEST_APPVEYOR_ENV%
    - echo Content of drive C
    - dir ..
    - set MSYS_DIR=C:\msys64
    - set MINGW_DIR=%MSYS_DIR%\mingw64
    - set PATH=%MINGW_DIR%\bin;%MSYS_DIR%\usr\bin;%PATH%
    - pacman -S --noconfirm --quiet mingw-w64-x86_64-gtk3
    - pacman -S --noconfirm --quiet mingw-w64-x86_64-gtkmm3

clone_folder: C:\gtk-test

artifacts:
    - path: .out\main.exe
      name: gtk-test.dependent.exe
      type: exe

matrix:
    fast_finish: true

services:
    - msys
    - bash
    - mingw

install:
    - cmd: npm install

platform:
    - Any CPU

configuration: Release

after_deploy:
    - echo After Deploy %TEST_APPVEYOR_ENV%
    - echo Current Working Directory %cd%
    - dir

build_script:
    - cmd: npm run build
